/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "tr111/tr111.h"
#include "cwmpd/include/cwmpd.h"

#ifdef ANDROID
#include <jni.h>
#include <android/log.h>
#define LOGE(format, ...)  __android_log_print(ANDROID_LOG_ERROR, "(>_<)", format, ##__VA_ARGS__)
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO,  "(=_=)", format, ##__VA_ARGS__)
#else
#define LOGE(format, ...)  printf("(>_<) " format "\n", ##__VA_ARGS__)
#define LOGI(format, ...)  printf("(^_^) " format "\n", ##__VA_ARGS__)
#endif



/*
 * Class:     com_zhangwoshenghuo_netcwmp_JniInter
 * Method:    tr111test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhangwoshenghuo_netcwmp_JniInter_tr111test
  (JNIEnv *env, jobject obj)
{

	test();

}

JNIEXPORT jint JNICALL Java_com_zhangwoshenghuo_netcwmp_JniInter_tr069launch
  (JNIEnv *env, jobject obj)
{
	LOGI("Now in the tr069launch\n");
	tr069launch(1,"haha");

}

