/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhangwoshenghuo_netcwmp_JniInter */

#ifndef _Included_com_zhangwoshenghuo_netcwmp_JniInter
#define _Included_com_zhangwoshenghuo_netcwmp_JniInter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhangwoshenghuo_netcwmp_JniInter
 * Method:    tr111test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhangwoshenghuo_netcwmp_JniInter_tr111test
  (JNIEnv *, jobject);

/*
 * Class:     com_zhangwoshenghuo_netcwmp_JniInter
 * Method:    tr069launch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhangwoshenghuo_netcwmp_JniInter_tr069launch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
